const trainingLegalQueries = [
    "Is it legal for an employer to monitor employee emails?",
    "Can my boss read my work emails?",
    "Are companies allowed to track employee messages?",
    "What are my privacy rights at work regarding email?",
    "Can my employer spy on my emails?",
    "Is workplace email monitoring legal?",
    "Can my employer monitor my work email without my consent?",
    "What laws protect employees from email surveillance?",
    "Do employers need permission to read employee emails?",
    "Is it legal for a company to access my work email?",
    "Can my employer track my internet usage at work?",
    "Can my employer see my personal emails sent from work?",
    "Are work emails considered private?",
    "What are the legal limits of employer email monitoring?",
    "Can a company monitor all employee communications?",
    "Are there any federal laws against email monitoring at work?",
    "Does my employer need a policy to monitor emails?",
    "Can an employer read emails sent from a personal account on a work computer?",
    "Are my emails at work subject to employer review?",
    "Can a boss look at my emails without telling me?",
    "Can my employer store my emails for later review?",
    "Is it a violation of privacy for my employer to read my emails?",
    "Can an employer check emails of a former employee?",
    "Do I have any legal protections against workplace email monitoring?",
    "What legal recourse do I have if my boss reads my emails?",
    "Can my employer use my emails against me in court?",
    "Does my employer have to inform me before monitoring emails?",
    "Is it legal for a company to access deleted work emails?",
    "Are there state laws restricting email surveillance by employers?",
    "Can an employer monitor private messages on a work laptop?",
    "Does the Fourth Amendment protect my work emails?",
    "Can I sue my employer for unauthorized email monitoring?",
    "Is employer monitoring of work emails different from phone calls?",
    "Can my boss intercept my emails before I see them?",
    "Is it legal to record employee emails for security reasons?",
    "Can a company monitor employee communications outside of work?",
    "Are my emails protected under the Electronic Communications Privacy Act?",
    "Can employers read my emails if I work remotely?",
    "Do remote employees have different email privacy rights?",
    "Can my employer check my Gmail if I use it at work?",
    "Can my employer see what I type in my emails in real-time?",
    "Are my work emails considered my employer’s property?",
    "Can my employer use email tracking software on my work email?",
    "Can an employer read my Slack or Teams messages?",
    "What are the legal restrictions on monitoring workplace chats?",
    "Is it legal to monitor employee text messages?",
    "Can a company monitor employee social media messages?",
    "Can my employer see my personal messages on a work phone?",
    "Are emails considered confidential under the law?",
    "Can my employer read my emails if I’m under investigation?",
    "Do public and private employees have different email privacy rights?",
    "What legal actions can I take if my employer violates my email privacy?",
    "Can an employer read emails between employees discussing work conditions?",
    "Are there specific laws preventing workplace email interception?",
    "Can my boss read my personal email if I log in on a work device?",
    "What legal steps can employees take against unfair email monitoring?",
    "Can my employer monitor my work email if I work from home?",
    "Do employers have to disclose email monitoring policies?",
    "Can my boss access my email inbox without a warrant?",
    "Does HIPAA protect employee emails in healthcare settings?",
    "Are government employees protected from email surveillance?",
    "Can my employer track who I email outside of work?",
    "Can my boss read my emails after I quit?",
    "Are emails considered personal property under labor law?",
    "Can my employer read my work emails on my phone?",
    "Are employers legally required to store employee emails?",
    "Can my employer be sued for violating email privacy?",
    "Do I have a right to know if my employer is reading my emails?",
    "Is an employer allowed to use work emails as evidence in a lawsuit?",
    "What penalties exist for companies that violate employee email privacy?"
  ];
  

module.exports = { trainingLegalQueries }